resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/concourse-maven-spring-boot.git
      branch: BBB

jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/concourse/tasks/package.yml
